[metadata]
name = hazen
version = attr: hazenlib._version.__version__
url = https://bitbucket.org/gsttmri/hazen
author = Shuaib, Haris
author_email = mohammad_haris.shuaib@kcl.ac.uk
description = An automatic MRI QA tool
long_description = file:README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.9,<3.14
install_requires =
    pydicom==3.0.1
    numpy>=2.3.1
    matplotlib>=3.10.8
    docopt==0.6.2
    opencv-python-headless==4.13.0.92
    scikit-image>=0.26.0
    scipy>=1.17.1
    imutils==0.5.4
    colorlog==6.7.0
include_package_data=True

[options.entry_points]
console_scripts =
    hazen = hazenlib:main
